apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ticketingtestprodrandom
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - jetstack
  secretName: ticketingtestprodrandom-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - ticketingtestprodrandom.xyz
    - www.ticketingtestprodrandom.xyz